--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

--DANCE MOVES
return {
	{Type="common",Skill="basic",Anim="Bob_DancingSillyA",Time=800},
	{Type="common",Skill="basic",Anim="Bob_DancingChicken",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingWaveHands",Time=900},
	{Type="common",Skill="basic",Anim="Bob_DancingSideStepLarge",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingRotatingA",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingHokeyPokey",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingMoveAround",Time=630},
	{Type="common",Skill="basic",Anim="Bob_DancingSideStepArmSwing",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingFootSwitch",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingCookingCauldron",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingSideToSide",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingFreestyleD",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingHandWave",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingSidestepSimple",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingSidestepLarge2",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingFreestyleG",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingClubSidestep",Time=630},
	{Type="common",Skill="basic",Anim="Bob_DancingClubFreestyleB",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingClubSideStepEnergetic",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingClubVibing",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingHandsInAir",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingRotatingC",Time=600},
	{Type="common",Skill="basic",Anim="Bob_DancingToAndFrom2",Time=600},

	{Type="common",Skill="intermediate",Anim="Bob_DancingSideStep",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingUprockA",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingGangnam",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingHouseB",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingHouseC",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingMoveAroundAndSpin",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingSpinInPlace",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingFreestyleA",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingFreestyleB",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingFreestyleC",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingFreestyleE",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingWave",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingLegTurnUp2",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingFreestyleH",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingFreestyleI",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingRotatingB",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingClubMoveAround",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleD",Time=600},
	{Type="common",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleH",Time=600},

	{Type="common",Skill="advanced",Anim="Bob_DancingSideStepEnergetic",Time=600},
	{Type="common",Skill="advanced",Anim="Bob_DancingAdvancedA",Time=600},
	{Type="common",Skill="advanced",Anim="Bob_DancingSpinInPlaceAdvanced",Time=600},
	{Type="common",Skill="advanced",Anim="Bob_DancingClubFreestyleA",Time=600},

	{Type="disco",Skill="basic",Anim="Bob_DancingDiscoDefault",Time=600},
	{Type="disco",Skill="basic",Anim="Bob_DancingDiscoDefaultB",Time=600},
	{Type="disco",Skill="basic",Anim="Bob_DancingDiscoDefaultC",Time=600},
	{Type="disco",Skill="basic",Anim="Bob_DancingDiscoBeachBasicA",Time=900},
	{Type="disco",Skill="basic",Anim="Bob_DancingSideToSide",Time=600},
	{Type="disco",Skill="basic",Anim="Bob_DancingYMCA",Time=600},
	{Type="disco",Skill="basic",Anim="Bob_DancingClubToAndFrom",Time=600},
	{Type="disco",Skill="basic",Anim="Bob_DancingHandDown",Time=600},
	{Type="disco",Skill="basic",Anim="Bob_DancingKick",Time=600},
	{Type="disco",Skill="basic",Anim="Bob_DancingSideStepWave",Time=600},

	{Type="disco",Skill="intermediate",Anim="Bob_DancingDiscoIntermediateA",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingDiscoIntermediateB",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingRunningMan",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingArmSwingUp",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingLegSweepLowMany",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingTipToeHeadUp",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingFreestyleA",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingRobotB",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingClubWobble",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingShake",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingFreestyleShake",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingDiscoWave2",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingHeadShake",Time=600},
	{Type="disco",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleC",Time=600},

	{Type="disco",Skill="advanced",Anim="Bob_DancingHouseA",Time=600},
	{Type="disco",Skill="advanced",Anim="Bob_DancingRobotA",Time=600},
	{Type="disco",Skill="advanced",Anim="Bob_DancingSlide",Time=600},
	{Type="disco",Skill="advanced",Anim="Bob_DancingThrillerB",Time=600},
	{Type="disco",Skill="advanced",Anim="Bob_DancingRobotC",Time=600},
	{Type="disco",Skill="advanced",Anim="Bob_DancingMoonwalk",Time=600},

	{Type="salsa",Skill="basic",Anim="Bob_DancingDiscoBeachBasicA",Time=900},
	{Type="salsa",Skill="basic",Anim="Bob_DancingCanCan",Time=600},
	{Type="salsa",Skill="basic",Anim="Bob_DancingMacarena",Time=600},
	{Type="salsa",Skill="basic",Anim="Bob_DancingClubWave",Time=600},
	{Type="salsa",Skill="basic",Anim="Bob_DancingClubRotateInPlace",Time=630},
	{Type="salsa",Skill="basic",Anim="Bob_DancingSideStepWave",Time=600},
	{Type="salsa",Skill="basic",Anim="Bob_DancingRotatingC",Time=600},
	{Type="salsa",Skill="basic",Anim="Bob_DancingToAndFrom2",Time=600},
	{Type="salsa",Skill="basic",Anim="Bob_DancingGraciously",Time=600},
	{Type="salsa",Skill="basic",Anim="Bob_DancingGraciously2",Time=600},
	{Type="salsa",Skill="basic",Anim="Bob_DancingBooty",Time=600},

	{Type="salsa",Skill="intermediate",Anim="Bob_DancingTwerk",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingWave",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingDiscoWave2",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleB",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleC",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingWaveEnergetic",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingClubMoveAround",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleD",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleE",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleH",Time=600},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingSalsaWave",Time=800},
	{Type="salsa",Skill="intermediate",Anim="Bob_DancingSalsaWaveMovingAround",Time=600},

	{Type="salsa",Skill="advanced",Anim="Bob_DancingBellyDancer",Time=600},
	{Type="salsa",Skill="advanced",Anim="Bob_DancingTwerkSnake",Time=600},
	{Type="salsa",Skill="advanced",Anim="Bob_DancingSalsaFreestyleF",Time=600},
	{Type="salsa",Skill="advanced",Anim="Bob_DancingSalsaFreestyleG",Time=600},
	{Type="salsa",Skill="advanced",Anim="Bob_DancingSalsaWaveFreestyle",Time=600},

	{Type="club",Skill="basic",Anim="Bob_DancingArmSwingUp",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingMacarena",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingMoveAroundAndSpin2",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingOrangutan",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingYMCA",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingFreestyleG",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingClubSidestep",Time=630},
	{Type="club",Skill="basic",Anim="Bob_DancingClubWave",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingClubToAndFrom",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingClubFreestyleB",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingClubSideStepEnergetic",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingClubRotateInPlace",Time=630},
	{Type="club",Skill="basic",Anim="Bob_DancingHandDown",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingClubVibing",Time=600},
	{Type="club",Skill="basic",Anim="Bob_DancingClubMoveAroundAxis",Time=600},

	{Type="club",Skill="intermediate",Anim="Bob_DancingHipHopIntermediateA",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingRunningMan",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingBreakDanceA",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingBreakDanceB",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingBreakDanceC",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingBreakDanceD",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingLegSweepUp",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingLegSweepLowMany",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingRobotB",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingFreestyleF",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingFreestyleH",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingClubWobble",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingShake",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingFreestyleShake",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingDiscoWave2",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingHeadShake",Time=600},
	{Type="club",Skill="intermediate",Anim="Bob_DancingSalsaFreestyleB",Time=600},

	{Type="club",Skill="advanced",Anim="Bob_DancingHeadspin",Time=600},
	{Type="club",Skill="advanced",Anim="Bob_DancingHouseA",Time=600},
	{Type="club",Skill="advanced",Anim="Bob_DancingRobotA",Time=600},
	{Type="club",Skill="advanced",Anim="Bob_DancingSlide",Time=600},
	{Type="club",Skill="advanced",Anim="Bob_DancingThrillerB",Time=600},
	{Type="club",Skill="advanced",Anim="Bob_DancingRobotC",Time=600},
	{Type="club",Skill="advanced",Anim="Bob_DancingClubFreestyleA",Time=600},

}

--Dances taken out (for now)
--Bob_DancingJumpsForward Bob_DancingRunLegSweep Bob_DancingSalsaWaveMoving Bob_DancingCarDrive Bob_DancingThrillerA Bob_DancingThrillerC Bob_DancingSideJumps Bob_DancingClubEnergetic Bob_DancingSuspendBody Bob_DancingSomersault Bob_DancingLegTurnUP Bob_DancingHeadSpin2 Bob_DancingSalsaFreestyle
