--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

--VOICE TRACKS
return {
	{Voice=0,Type="Booing",sound="ManBooing01",soundF="WomanBooing01"},
	{Voice=0,Type="Booing",sound="ManBooing02",soundF="WomanBooing02"},
	{Voice=0,Type="Booing",sound="ManBooing03",soundF="WomanBooing03"},
	{Voice=1,Type="Booing",sound="ManBooing11",soundF="WomanBooing11"},
	{Voice=1,Type="Booing",sound="ManBooing12",soundF="WomanBooing12"},
	{Voice=1,Type="Booing",sound="ManBooing13",soundF="WomanBooing13"},
	{Voice=2,Type="Booing",sound="ManBooing21",soundF="WomanBooing21"},
	{Voice=2,Type="Booing",sound="ManBooing22",soundF="WomanBooing22"},
	{Voice=2,Type="Booing",sound="ManBooing23",soundF="WomanBooing23"},
	{Voice=3,Type="Booing",sound="ManBooing31",soundF="WomanBooing31"},
	{Voice=3,Type="Booing",sound="ManBooing32",soundF="WomanBooing32"},
	{Voice=3,Type="Booing",sound="ManBooing33",soundF="WomanBooing33"},
	{Voice=4,Type="Booing",sound="ManBooing41",soundF="WomanBooing41"},
	{Voice=4,Type="Booing",sound="ManBooing42",soundF="WomanBooing42"},
	{Voice=4,Type="Booing",sound="ManBooing43",soundF="WomanBooing43"},
	{Voice=0,Type="Frustrated",sound="ManFrustrated01",soundF="WomanFrustrated01"},
	{Voice=0,Type="Frustrated",sound="ManFrustrated02",soundF="WomanFrustrated02"},
	{Voice=0,Type="Frustrated",sound="ManFrustrated03",soundF="WomanFrustrated03"},
	{Voice=1,Type="Frustrated",sound="ManFrustrated11",soundF="WomanFrustrated11"},
	{Voice=1,Type="Frustrated",sound="ManFrustrated12",soundF="WomanFrustrated12"},
	{Voice=1,Type="Frustrated",sound="ManFrustrated13",soundF="WomanFrustrated13"},
	{Voice=2,Type="Frustrated",sound="ManFrustrated21",soundF="WomanFrustrated21"},
	{Voice=2,Type="Frustrated",sound="ManFrustrated22",soundF="WomanFrustrated22"},
	{Voice=2,Type="Frustrated",sound="ManFrustrated23",soundF="WomanFrustrated23"},
	{Voice=3,Type="Frustrated",sound="ManFrustrated31",soundF="WomanFrustrated31"},
	{Voice=3,Type="Frustrated",sound="ManFrustrated32",soundF="WomanFrustrated32"},
	{Voice=3,Type="Frustrated",sound="ManFrustrated33",soundF="WomanFrustrated33"},
	{Voice=4,Type="Frustrated",sound="ManFrustrated41",soundF="WomanFrustrated41"},
	{Voice=4,Type="Frustrated",sound="ManFrustrated42",soundF="WomanFrustrated42"},
	{Voice=4,Type="Frustrated",sound="ManFrustrated43",soundF="WomanFrustrated43"},
	{Voice=0,Type="Woohoo",sound="ManWoohoo01",soundF="WomanWoohoo01"},
	{Voice=0,Type="Woohoo",sound="ManWoohoo02",soundF="WomanWoohoo02"},
	{Voice=0,Type="Woohoo",sound="ManWoohoo03",soundF="WomanWoohoo03"},
	{Voice=1,Type="Woohoo",sound="ManWoohoo11",soundF="WomanWoohoo11"},
	{Voice=1,Type="Woohoo",sound="ManWoohoo12",soundF="WomanWoohoo12"},
	{Voice=1,Type="Woohoo",sound="ManWoohoo13",soundF="WomanWoohoo13"},
	{Voice=2,Type="Woohoo",sound="ManWoohoo21",soundF="WomanWoohoo21"},
	{Voice=2,Type="Woohoo",sound="ManWoohoo22",soundF="WomanWoohoo22"},
	{Voice=2,Type="Woohoo",sound="ManWoohoo23",soundF="WomanWoohoo23"},
	{Voice=3,Type="Woohoo",sound="ManWoohoo31",soundF="WomanWoohoo31"},
	{Voice=3,Type="Woohoo",sound="ManWoohoo32",soundF="WomanWoohoo32"},
	{Voice=3,Type="Woohoo",sound="ManWoohoo33",soundF="WomanWoohoo33"},
	{Voice=4,Type="Woohoo",sound="ManWoohoo41",soundF="WomanWoohoo41"},
	{Voice=4,Type="Woohoo",sound="ManWoohoo42",soundF="WomanWoohoo42"},
	{Voice=4,Type="Woohoo",sound="ManWoohoo43",soundF="WomanWoohoo43"},
	{Voice=0,Type="Dancing",happy="ManDanceHappy01",happyF="WomanDanceHappy01"},
	{Voice=0,Type="Dancing",happy="ManDanceHappy02",happyF="WomanDanceHappy02"},
	{Voice=0,Type="Dancing",happy="ManDanceHappy02",happyF="WomanDanceHappy03"},
	{Voice=0,Type="Dancing",happy="ManDanceHappy04",happyF="WomanDanceHappy04"},
	{Voice=1,Type="Dancing",happy="ManDanceHappy11",happyF="WomanDanceHappy11"},
	{Voice=1,Type="Dancing",happy="ManDanceHappy12",happyF="WomanDanceHappy12"},
	{Voice=1,Type="Dancing",happy="ManDanceHappy12",happyF="WomanDanceHappy13"},
	{Voice=1,Type="Dancing",happy="ManDanceHappy14",happyF="WomanDanceHappy14"},
	{Voice=2,Type="Dancing",happy="ManDanceHappy21",happyF="WomanDanceHappy21"},
	{Voice=2,Type="Dancing",happy="ManDanceHappy22",happyF="WomanDanceHappy22"},
	{Voice=2,Type="Dancing",happy="ManDanceHappy22",happyF="WomanDanceHappy23"},
	{Voice=2,Type="Dancing",happy="ManDanceHappy24",happyF="WomanDanceHappy24"},
	{Voice=3,Type="Dancing",happy="ManDanceHappy31",happyF="WomanDanceHappy31"},
	{Voice=3,Type="Dancing",happy="ManDanceHappy32",happyF="WomanDanceHappy32"},
	{Voice=3,Type="Dancing",happy="ManDanceHappy32",happyF="WomanDanceHappy33"},
	{Voice=3,Type="Dancing",happy="ManDanceHappy34",happyF="WomanDanceHappy34"},
	{Voice=4,Type="Dancing",happy="ManDanceHappy41",happyF="WomanDanceHappy41"},
	{Voice=4,Type="Dancing",happy="ManDanceHappy42",happyF="WomanDanceHappy42"},
	{Voice=4,Type="Dancing",happy="ManDanceHappy42",happyF="WomanDanceHappy43"},
	{Voice=4,Type="Dancing",happy="ManDanceHappy44",happyF="WomanDanceHappy44"},
}
